language: php

php:
  - 7.1

# env:
#   global:
#     - APP_ENV=testing
#     - APP_KEY=abcdefghijklmnopqrstuvwxyz123456
#     - DB_CONNECTION=testing
#     - DB_TEST_USERNAME=root
#     - DB_TEST_PASSWORD=
#     - CACHE_DRIVER=array
#     - SESSION_DRIVER=array
#     - QUEUE_DRIVER=sync

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

services:
  - memcached
  - redis-server

before_install:
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - travis_retry composer self-update

before_script:
  - cp .env.travis .env
  - cat .env
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit