language: php

php:
  - 7.1

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

services:
  - memcached
  - redis-server

before_install:
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - travis_retry composer self-update

before_script:
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit